name: "Folder Test Runner"
description: "Triggers folder test run and polls for completion status"
author: "Autonoma AI"
branding:
  icon: "folder"
  color: "green"
inputs:
  folder-id:
    description: "Folder id to run test"
    required: true
  client-id:
    description: "Autonoma client ID for API authentication"
    required: true
  client-secret:
    description: "Autonoma client secret for API authentication"
    required: true
  max-wait-time:
    description: "Maximum wait time in minutes before timeout (range: 10-20 minutes)"
    required: false
    default: "10"
outputs:
  run-id:
    description: "ID of the test run returned by API"
    value: ${{ steps.run-tests.outputs.run-id }}
  final-status:
    description: "Final status of the test run"
    value: ${{ steps.poll-status.outputs.final-status }}
  message:
    description: "Status message from the test run"
    value: ${{ steps.poll-status.outputs.message }}
  url:
    description: "URL to view test results"
    value: ${{ steps.poll-status.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Trigger Folder Test Run
      id: run-tests
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/../scripts/run-test.sh
        ${{ github.action_path }}/../scripts/run-test.sh \
          "https://autonoma.app/api/run/folder" \
          "${{ inputs.folder-id }}" \
          "${{ inputs.max-wait-time }}" \
          "${{ inputs.client-id }}" \
          "${{ inputs.client-secret }}"
    - name: Poll Test Status
      id: poll-status
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/../scripts/poll-status.sh
        ${{ github.action_path }}/../scripts/poll-status.sh \
          "https://autonoma.app/api/run/folder" \
          "${{ steps.run-tests.outputs.run-id }}" \
          "${{ inputs.max-wait-time }}" \
          "${{ inputs.client-id }}" \
          "${{ inputs.client-secret }}" \
          "folder"
