name: "Folder Test Runner"
description: "Triggers folder/directory test run and polls for completion status"
author: "Autonoma ai"
branding:
  icon: "folder"
  color: "green"
inputs:
  folder-id:
    description: "Folder id to run test"
    required: true
  client-id:
    description: "Autonoma client ID for API authentication"
    required: true
  client-secret:
    description: "Autonoma client secret for API authentication"
    required: true
  max-wait-time:
    description: "Maximum wait time in minutes before timeout (range: 10-20 minutes)"
    required: false
    default: "10"
outputs:
  run-id:
    description: "ID of the test run (if returned by API)"
  final-status:
    description: "Final status of the test run"
runs:
  using: "composite"
  steps:
    - name: Trigger Folder Test Run
      id: run-tests
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/../scripts/trigger-tests.sh
        ${{ github.action_path }}/../scripts/trigger-tests.sh \
          "https://api.prod.autonoma.app/api/run/folder" \
          "${{ inputs.folder-id }}" \
          "${{ inputs.max-wait-time }}" \
          "${{ inputs.client-id }}" \
          "${{ inputs.client-secret }}"
    - name: Poll Test Status
      id: poll-status
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/../scripts/poll-status.sh
        ${{ github.action_path }}/../scripts/poll-status.sh \
          "https://api.yourservice.com/api/folders/status" \
          "${{ inputs.max-wait-time }}" \
          "${{ inputs.client-id }}" \
          "${{ inputs.client-secret }}" \
          "${{ steps.run-tests.outputs.run-id }}"
